### PR TITLE
Fix conflict between laguna, numericalsgps, alcove

### PR DESCRIPTION
**Pull request by fingolfin**
This broke package tests. @alex-konovalov OK to merge this and make a re-release? I'll submit similar PRs to the other two packages

### CODE REVIEW

**Comment by fingolfin** [comment]
Hrmmm... Actually... the more I think about it, the less clear it is to me *how* to do this migration, though: we kinda need to update all three packages at once. This PR only "fixes" the case where one of the other two packages are loaded first. But if LAGUNA is loaded first, this doesn't help at all. Ugh. So perhaps we should just forget about this PR...

**Comment by fingolfin** [comment]
All in all, I think it is better and easier to just plow ahead and update all the packages together... See https://github.com/gap-packages/unitlib/pull/24 ...

**Comment by olexandr-konovalov** [comment]
@fingolfin tests look good now?

**Comment by fingolfin** [comment]
I don't think we need or even want this PR now, though, with the other package having adapted to the new Laguna? This PR here is insufficient to deal with all cases anyway, and it depends on the loading order

**Comment by olexandr-konovalov** [comment]
@fingolfin Ah, ok. Then I can proceed to making a new release without this PR.

**Pull request closed without merging**
